#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-nekohtml
Version  : 1.9.6.2
Release  : 5
URL      : https://repo1.maven.org/maven2/nekohtml/nekohtml/1.9.6.2/nekohtml-1.9.6.2.jar
Source0  : https://repo1.maven.org/maven2/nekohtml/nekohtml/1.9.6.2/nekohtml-1.9.6.2.jar
Source1  : https://repo.gradle.org/gradle/libs-releases/net/sourceforge/nekohtml/nekohtml/1.9.14/nekohtml-1.9.14.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/net/sourceforge/nekohtml/nekohtml/1.9.14/nekohtml-1.9.14.pom
Source3  : https://repo.gradle.org/gradle/libs-releases/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.jar
Source4  : https://repo.gradle.org/gradle/libs-releases/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.pom
Source5  : https://repo1.maven.org/maven2/nekohtml/nekohtml/1.9.6.2/nekohtml-1.9.6.2.pom
Source6  : https://repo1.maven.org/maven2/net/sourceforge/nekohtml/nekohtml/1.9.22/nekohtml-1.9.22.jar
Source7  : https://repo1.maven.org/maven2/net/sourceforge/nekohtml/nekohtml/1.9.22/nekohtml-1.9.22.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-nekohtml-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-nekohtml package.
Group: Data

%description data
data components for the mvn-nekohtml package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/nekohtml/nekohtml/1.9.6.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/nekohtml/nekohtml/1.9.6.2/nekohtml-1.9.6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.14
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.14/nekohtml-1.9.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.14
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.14/nekohtml-1.9.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.16
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.16
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/nekohtml/nekohtml/1.9.6.2
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/nekohtml/nekohtml/1.9.6.2/nekohtml-1.9.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.22
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.22/nekohtml-1.9.22.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.22
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.22/nekohtml-1.9.22.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/nekohtml/nekohtml/1.9.6.2/nekohtml-1.9.6.2.jar
/usr/share/java/.m2/repository/nekohtml/nekohtml/1.9.6.2/nekohtml-1.9.6.2.pom
/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.14/nekohtml-1.9.14.jar
/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.14/nekohtml-1.9.14.pom
/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.jar
/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.pom
/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.22/nekohtml-1.9.22.jar
/usr/share/java/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.22/nekohtml-1.9.22.pom
